/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CookieGetter {
        "boutontitle": string;
        "informationtext": string;
        "logotitle": string;
        "modalcontent": string;
        "src": string;
    }
    interface MyComponent {
        "display": () => Promise<void>;
        "name": string;
    }
}
declare global {
    interface HTMLCookieGetterElement extends Components.CookieGetter, HTMLStencilElement {
    }
    var HTMLCookieGetterElement: {
        prototype: HTMLCookieGetterElement;
        new (): HTMLCookieGetterElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "cookie-getter": HTMLCookieGetterElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface CookieGetter {
        "boutontitle"?: string;
        "informationtext"?: string;
        "logotitle"?: string;
        "modalcontent"?: string;
        "src"?: string;
    }
    interface MyComponent {
        "name"?: string;
    }
    interface IntrinsicElements {
        "cookie-getter": CookieGetter;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "cookie-getter": LocalJSX.CookieGetter & JSXBase.HTMLAttributes<HTMLCookieGetterElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
